### ISSUE TITLE
ValidationError when posting minimal_sales_invoice to Netvisor demo enviroment

### ISSUE THREAD

**Issue by tristen-tooming** [Heltti/netvisor-api-client#2]
Hey,

I am getting this error when posting  "minimal_sales_invoice" to Netvisor demo enviroment:
marshmallow.exceptions.ValidationError: {'invoice_lines': {'product_identifier': {'_schema': ["Unknown field name: '1'"]}}}

The items customer code is: 1697
and netvisor id: 6

But both of does not work

**Comment by tristen-tooming** [comment]
.sales_invoices.create() works with version 0.7 but not with 0.8.4

**Comment by ajmyyra** [comment]
Kind of an old issue, but could you check if this still happens? I tried reproducing the problem, so I'm assuming that it has been fixed in some of the later versions.

**Comment by tristen-tooming** [comment]
Yes, kind of an old issue and newer versions are working for me. I think we can close this?
